---
title: "Webapp"
output: html_document
date: "2023-04-05"
---
## Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library(shiny)
library(shinythemes)
library(shinydashboard)
library(leaflet)
library(leaflet.extras)
library(leaflet.minicharts)
library(dplyr)
library(readr)
library(htmltools)
library(stringr)
library(plotly)
library(maptools)
library(ggfortify)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyr)

data_clean <- read_csv("../NTSB-Aircraft_Accidents/Datasets/Cleaned_Data.csv")
Airport_SIR <- read_csv("../NTSB-Aircraft_Accidents/Datasets/Airport_SIR.csv")
```

# Webapp Code
```{r}
  ui = navbarPage(title = tags$div(tags$h1("NTSB Small Aircraft Dashboard", style = "background-color : #7F1826 ; font-family: Roboto; font-style: italic; color : white ; text-shadow: 3px -1px 0 rgba(0, 0, 0, 0.5); font-size: 20px; top : 0px; margin-top : 0 px;"),
       tags$img(img(src = "image/wsuicon.png", height = "98px", style = "position: absolute; right : 0px; top : 0px"))),
       

                  
##################   HEATMAP    #################
                                          
  tabPanel("Geographical Heatmap",
    textOutput('heatmap_title'),
      tags$head(tags$style("#heatmap_title{color:black;
                                 font-size: 20px;
                                 font-style: bold;
                                 text-align: center;
                                 margin-bottom: 10px;
                                 }" 
                           ,".navbar{background-color:#7F1826}",
                           "body {background-color: lightgrey;
                           }"
                         )
              ),
    textOutput('heatmap_summary'), 
     tags$head(tags$style("#heatmap_summary{color:black;
                                 font-size: 13px;
                                 margin-bottom: 20px;
                                 }"
                         )
            ),
    plotlyOutput('heatmap', height = "80%")),

##################. INTERACTIVE HEATMAP   ####################

  tabPanel("Interactive Heatmap",
           dashboardPage(
               dashboardHeader(title = "Options"),
               dashboardSidebar(
                 checkboxInput("ShowAirportCodes", label = "Show Airport Codes", value = FALSE, width = NULL),
                 selectInput("FlightType", "Flight Type", c("All", "Personal", "Instructional", "Aerial Application"), selected = "All"),
                 sliderInput("SIRThreshold", "SIR Min Threshold", min = 0, max = 10, value = 1)
               
                 ),
               dashboardBody(
                 # Add the leaflet map to the main body of the dashboard
                 textOutput('map_summary'),
                 leafletOutput('heatmapleaflet'),
                 
                 tags$head(tags$style(HTML('
        /* logo */
        .skin-blue .main-header .logo {
                              background-color: #7F1826;
                              }

        /* logo when hovered */
        .skin-blue .main-header .logo:hover {
                              background-color: #7F1826;
                              }

        /* navbar (rest of the header) */
        .skin-blue .main-header .navbar {
                              background-color: #7F1826;
                              }        

        /* main sidebar */
        .skin-blue .main-sidebar {
                              background-color: #888888; height : 50px;
                              }

        /* active selected tab in the sidebarmenu */
        .skin-blue .main-sidebar .sidebar .sidebar-menu .active a{
                              background-color: #7F1826;
                              }

        /* other links in the sidebarmenu */
        .skin-blue .main-sidebar .sidebar .sidebar-menu a{
                              background-color: #00ff00;
                              color: #000000;
                              }

        /* other links in the sidebarmenu when hovered */
         .skin-blue .main-sidebar .sidebar .sidebar-menu a:hover{
                              background-color: #7F1826;
                              }
        /* toggle button when hovered  */                    
         .skin-blue .main-header .navbar .sidebar-toggle:hover{
                              background-color: #7F1826;
                              }
                              ')))
                )
                 
               )
             
           ),

##############   Airport SIR Map    ##################
  tabPanel("Airport Severity Index Rating Map", 
    textOutput('SIR_title'),
      tags$head(tags$style("#SIR_title{color:black;
                                 font-size: 20px;
                                 font-style: bold;
                                 text-align: center;
                                 margin-bottom: 10px;
                                 }"
                         )
            ), 
    textOutput('SIR_summary'),
      tags$head(tags$style("#SIR_summary{color:black;
                                 font-size: 13px;
                                 margin-bottom: 15px;
                                 }"
                         )
            ),
    textOutput('SIR_formula'),
      tags$head(tags$style("#SIR_formula{color:black;
                                 font-size: 14px;
                                 font-style: italic;
                                 text-align: center;
                                 margin-top: 10px;
                                 margin-bottom: 15px;
                                 }"
                         )
            ), 
    plotlyOutput('SIRmap', height = "80%")),

#########    MANUFACTURERS BOXPLOT  ############
  tabPanel("Boxplot SIR Comparison", dashboardPage(
               dashboardHeader(title = "Options"),
               dashboardSidebar(
                 checkboxInput("ShowAverageSIR", label = "Show Average", value = FALSE, width = NULL),
                 selectInput("CategorySwitch", "Category", c("Manufacturer", "Flight Type", "Weather Conditions", "Month", "Airport"), selected = "Manufacturer"),
                 verbatimTextOutput('boxplot_description')
               ),
                 dashboardBody(
                 textOutput('boxplot_summary'),
                  tags$head(tags$style("#SIR_summarya{color:black;
                                 font-size: 13px;
                                 margin-bottom: 20px;
                                 }"
                         )
            ), plotOutput('boxplot'))
               )),

#####   WEATHER CONDITIONS      #####

  tabPanel("Weather Conditions",
    textOutput('weather_title'),
      tags$head(tags$style("#weather_title{color:black;
                                 font-size: 20px;
                                 font-style: bold;
                                 text-align: center;
                                 margin-bottom: 10px;
                                 }"
                         )
            ),
      textOutput('weather_summary'), 
        tags$head(tags$style("#weather_summary{color:black;
                                 font-size: 13px;
                                 margin-bottom: 20px;
                                 }"
                         )
            ),
      plotOutput('weather'))
)



server = function(input,output,session) {
  
####       Heatmap Title     ####
    output$heatmap_title <- renderText("Geographical Heatmap")
    
####       Heatmap Summary     ####
    output$heatmap_summary <- renderText("This hotspot map displays the location where every small airplane accident occured within the U.S. As we can see there are accident hotspots in nearly all major metropolitan areas across the United States. The most significant hotspots are in Seattle, San Francisco, Los Angeles, New York, and the southern Florida coast.")
  
  
#####            HEATMAP PLOT   ###############
    output$heatmap <- renderPlotly({

usa <- ne_states(country="united states of america", returnclass = 'sf')
lat_long_df = data.frame(data_clean$Longitude,data_clean$Latitude,data_clean$Event.Id)
colnames(lat_long_df) <- c('Longitude','Latitude','Event.Id')
lat_long_df <- lat_long_df %>% filter(Longitude != "N/A", Longitude != "NA", Latitude != "N/A", Latitude != "NA")
      
USA_hotspots = ggplot(data = usa) +
  geom_sf() +
  geom_point(data = lat_long_df, aes(x = Longitude, y = Latitude), shape=16, colour = "darkred", size = 0.1) + coord_sf(xlim=c(-125,-67), ylim=c(24,49), expand=T) + theme(plot.title = element_text(hjust = 0.5))

ggplotly(USA_hotspots)

  })

############     INTERACTIVE HEATMAP      ##############
    
    output$heatmapleaflet <- renderLeaflet({
      map <- leaflet(na.omit(data_clean)) %>%
      addTiles() %>%
      addHeatmap(
        lat = ~Latitude,
        lng = ~Longitude,
        intensity = ~SIR,
        minOpacity = 0.05,
        max = 1,
        radius = 8
      ) %>%
      setView(lng = -96, lat = 37.8, zoom = 4)
    })
    
    output$map_summary <- renderText("The Geographical Heatmap below shows a graphical plot of small aircraft incidents in the United States. The color of the gradient indicates the severity of the incident (high number of fatalities = red). Incidents can be filtered by the flight type in sidebar. SIR threshold control shows only incidents that have occured above a certain SIR (1 is mild, above 3 is considered severe)")

####       SIR Title     ####
    output$SIR_title <- renderText("Airport Severity Index Rating Map") 
       
####       SIR Formula     ####
    output$SIR_formula <- renderText("Severity Index Rating = (Total Fatal Injuries x 3) + (Total Serious Injuries x 1.8) + (Total Minor Injuries x 1.3) + Total Uninjured")
    
####       SIR Summary     ####
    output$SIR_summary <- renderText("To create the severity index rating map, we first calculated the severity index for each incident using the below severity index rating formula. Then, the average severity index rating was calculated for each U.S. airport that had an incident reported to the NTSB. This average rating for each airport was plotted onto the map of the U.S. using the airports coordinates.")
    
#########   Severity Index Map    ################ 
    
    output$SIRmap <- renderPlotly({
usa <- ne_states(country="united states of america", returnclass = 'sf')

SIR_map = ggplot(data = usa) +
  geom_sf() +
  geom_point(data = Airport_SIR, aes(label=Airport.Name, color=Severity.Index.Rating, size=Severity.Index.Rating, x = Longitude, y = Latitude), shape=20) + scale_color_gradient(low = "grey", high = "darkred") + labs(color = "Severity Index Rating") + coord_sf(xlim=c(-125,-67), ylim=c(24,49), expand=T) + theme(plot.title = element_text(hjust = 0.5))


ggplotly(SIR_map)

    })
    
####     BOXPLOT SUMMARY     ############
    output$boxplot_summary <- renderText("Below, SIR values are compared among categories. The control on the left \nside bar allows the user to change categories of comparison.")
    
    output$boxplot_description <- renderText("Boxplot interpretation:
\nThe center line of the Box
in the boxplot indicates the
median (50thpercentile) where
the data is essentially split
in half (50% above, 50% below)
The upper and lower sides of
the box indicate the IQR (25%,
75%). The dots above each plot
indicate outliers (incidents of
above average values of SIR that
do not fit normally in model).")
    
#########          BOXPLOT        ################
data_clean$Make <- str_to_title(tolower(data_clean$Make))
data_clean$Airport.Name <- str_to_title(tolower(data_clean$Airport.Name))
data_clean$Airport.Name = ifelse(data_clean$Airport.Name %in% c("Centennial"), "Centennial Airport", data_clean$Airport.Name)
data_clean$Make <- ifelse(data_clean$Make == "Air Tractor Inc", "Air Tractor", data_clean$Make)
output$boxplot <- renderPlot({    
    Manufacturers <- (data_clean %>% group_by(Make) %>% count()) %>% filter(n > 100)

##Manufacturer vs SIR
new <- data_clean %>% filter(Make %in% Manufacturers$Make)

ggplot(data=new, mapping=aes(y = SIR, x = Make, fill = Make)) +
  geom_boxplot(show.legend = FALSE) +
  ylim(min = 0, max = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = .5)) +
  labs(title = "Severity Index Rating for Various Large Manufacturers", y = "SIR", x = "Manufacturer" )
  
  })

####       Weather Title     ####
    output$weather_title <- renderText("Weather Conditions")

####     WEATHER SUMMARY     ############
    output$weather_summary <- renderText("The weather condition plot explored the difference between Instrument Meteorological Conditions (IMC) and Visual Meteorological Conditions (VMC) regarding flight accidents during different phases of flight. According to the FAA, both IMC and VMC refer to the actual weather and is based on terms of visibility, and the distance from the cloud. VMC allows pilots to fly on their own without any assistance from air traffic control. IMC is used by an instrument-rated pilot for all flights. In the plot during each phase of flight many of the accidents happened when they were being controlled by the pilots. However, each phase has a small percentage of accidents when the aircraft was controlled by an instrument such as an attitude indicator and/or flight management systems.")
    
#########   WEATHER CONDITIONS    ############

output$weather <- renderPlot({

data_clean %>%
  mutate(Weather.Condition = case_when(Weather.Condition == "IMC" ~ "IMC (Instrument)", Weather.Condition == "VMC" ~ "VMC (Visual)"))%>%filter(Broad.phase.of.flight != "NA", Broad.phase.of.flight != "N/A", Broad.phase.of.flight != "Unknown", Broad.phase.of.flight != "Other")%>%
  drop_na()%>%
  group_by(Broad.phase.of.flight, Weather.Condition)%>%
  summarise(n = n())%>%
  mutate(freq = n/sum(n))%>%
  ggplot(aes(x= Weather.Condition, y = freq, fill = Weather.Condition, label = scales::percent(freq)))+geom_bar(stat = "identity")+facet_wrap("Broad.phase.of.flight")+labs(title = "Weather conditions of different phases of flight accidents", y = "Frequency", x = "Weather Conditions")+scale_fill_discrete(name = "Meteorological Conditions")+scale_y_continuous(labels = scales::percent)+geom_col(position= "dodge")+geom_text(position = position_stack(vjust=0.5))
})

############### Event Triggers. #######################################

observeEvent(input$ShowAirportCodes, {
  
  if (input$ShowAirportCodes){
  leafletProxy("heatmapleaflet", session) %>%
      clearMarkerClusters() %>%
      addLabelOnlyMarkers(
                       data = Airport_SIR,
                       lat = ~Latitude, 
                       lng = ~Longitude, 
                       label = ~Airport.Code,
                       group = "AirportCodes",
                       labelOptions = labelOptions(noHide = T, direction = 'top', textOnly = F))
} else {
    # Hide markers
    leafletProxy("heatmapleaflet", session) %>%
      clearGroup("AirportCodes")
  }
  })

observeEvent(input$FlightType, {
  
  if (input$FlightType == "All"){
    data = data_clean
  } else if (input$FlightType == "Personal") {
    data = subset(data_clean, Purpose.of.flight == "Personal")
  } else if (input$FlightType == "Aerial Application") {
    data = subset(data_clean, Purpose.of.flight == "Aerial Application")
  } else if (input$FlightType == "Instructional") {
    data = subset(data_clean, Purpose.of.flight == "Instructional")
  }
  
  leafletProxy("heatmapleaflet", session) %>%
    clearHeatmap() %>%
    addHeatmap(
        data = na.omit(data),
        lat = ~Latitude,
        lng = ~Longitude,
        intensity = ~SIR,
        minOpacity = 0.05,
        max = 1,
        radius = 8
    )
    })

observeEvent(input$SIRThreshold, {
    data = na.omit(subset(data_clean, SIR > input$SIRThreshold))
    leafletProxy("heatmapleaflet", session) %>%
    clearHeatmap() %>%
    addHeatmap(
        data = data,
        lat = ~Latitude,
        lng = ~Longitude,
        intensity = ~SIR,
        minOpacity = 0.05,
        max = 1,
        radius = 8
    )
  })

observeEvent(input$CategorySwitch, {
  
  if (input$CategorySwitch == "Manufacturer"){
    data = ((data_clean %>% group_by(Make) %>% count()) %>% filter(n > 100))
    data = data_clean %>% filter(Make %in% data$Make)
    category = data$Make
    categoryname = "Manufacturer"
  } else if (input$CategorySwitch == "Flight Type") {
    data = data_clean[complete.cases(data_clean$Purpose.of.flight), ]
    categoryname = "Purpose of Flight"
    category = data$Purpose.of.flight
  } else if (input$CategorySwitch == "Weather Conditions") {
    data = data_clean[complete.cases(data_clean$Weather.Condition), ]
    category = data$Weather.Condition
    categoryname = "Weather"
  } else if (input$CategorySwitch == "Month") {
    data = data_clean
    category = data$Month
    categoryname = "Month"
  } else if (input$CategorySwitch == "Airport") {
    data = ((data_clean %>% group_by(Airport.Name) %>% count()) %>% filter(n > 18))
    data = data_clean %>% filter(Airport.Name %in% data$Airport.Name)
    data$Airport.Name = ifelse(data$Airport.Name %in% c("N/A","None"), NA, data$Airport.Name)
    data$Airport.Name = ifelse(data$Airport.Name %in% c("Private", "Private Strip", "Pvt"), "Private Airstrip", data$Airport.Name)
    data = data[complete.cases(data$Airport.Name), ]
    category = data$Airport.Name
    categoryname = "Airport"
  }
  
  output$boxplot <- renderPlot({
ggplot(data=data, mapping=aes(y = SIR, x = category, fill = "darkred")) +
  geom_boxplot(show.legend = FALSE) +
  ylim(min = 0, max = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = .5)) +
  labs(title = paste("Severity Index Rating Comparison for Category: ", categoryname), y = "SIR", x = categoryname )
  
  })

})

observeEvent(input$ShowAverageSIR, {
  if (input$ShowAverageSIR){
      if (input$CategorySwitch == "Manufacturer"){
    data = ((data_clean %>% group_by(Make) %>% count()) %>% filter(n > 100))
    data = data_clean %>% filter(Make %in% data$Make)
    category = data$Make
    categoryname = "Manufacturer"
  } else if (input$CategorySwitch == "Flight Type") {
    data = data_clean[complete.cases(data_clean$Purpose.of.flight), ]
    categoryname = "Purpose of Flight"
    category = data$Purpose.of.flight
  } else if (input$CategorySwitch == "Weather Conditions") {
    data = data_clean[complete.cases(data_clean$Weather.Condition), ]
    category = data$Weather.Condition
    categoryname = "Weather"
  } else if (input$CategorySwitch == "Month") {
    data = data_clean
    category = data$Month
    categoryname = "Month"
  } else if (input$CategorySwitch == "Airport") {
    data = ((data_clean %>% group_by(Airport.Name) %>% count()) %>% filter(n > 18))
    data = data_clean %>% filter(Airport.Name %in% data$Airport.Name)
    data$Airport.Name = ifelse(data$Airport.Name %in% c("N/A","None"), NA, data$Airport.Name)
    data$Airport.Name = ifelse(data$Airport.Name %in% c("Private", "Private Strip","Pvt"), "Private Airstrip", data$Airport.Name)
    data = data[complete.cases(data$Airport.Name), ]
    category = data$Airport.Name
    categoryname = "Airport"
  }
  
  output$boxplot <- renderPlot({
ggplot(data=data, mapping=aes(y = SIR, x = category, fill = "darkred")) +
  geom_boxplot(show.legend = FALSE) +
  ylim(min = 0, max = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = .5)) +
  labs(title = paste("Severity Index Rating Comparison for Category: ", categoryname), y = "SIR", x = categoryname ) + geom_hline(yintercept = mean(data_clean$SIR), linetype = "dashed", color = "blue", linewidth = 1.2)
  })
} else {
        if (input$CategorySwitch == "Manufacturer"){
    data = ((data_clean %>% group_by(Make) %>% count()) %>% filter(n > 100))
    data = data_clean %>% filter(Make %in% data$Make)
    category = data$Make
    categoryname = "Manufacturer"
  } else if (input$CategorySwitch == "Flight Type") {
    data = data_clean[complete.cases(data_clean$Purpose.of.flight), ]
    categoryname = "Purpose of Flight"
    category = data$Purpose.of.flight
  } else if (input$CategorySwitch == "Weather Conditions") {
    data = data_clean[complete.cases(data_clean$Weather.Condition), ]
    category = data$Weather.Condition
    categoryname = "Weather"
  } else if (input$CategorySwitch == "Month") {
    data = data_clean
    category = data$Month
    categoryname = "Month"
  } else if (input$CategorySwitch == "Airport") {
    data = ((data_clean %>% group_by(Airport.Name) %>% count()) %>% filter(n > 18))
    data = data_clean %>% filter(Airport.Name %in% data$Airport.Name)
    data$Airport.Name = ifelse(data$Airport.Name %in% c("N/A","None"), NA, data$Airport.Name)
    data$Airport.Name = ifelse(data$Airport.Name %in% c("Private", "Private Strip","Pvt"), "Private Airstrip", data$Airport.Name)
    data = data[complete.cases(data$Airport.Name), ]
    category = data$Airport.Name
    categoryname = "Airport"
  }
  
  output$boxplot <- renderPlot({
ggplot(data=data, mapping=aes(y = SIR, x = category, fill = "darkred")) +
  geom_boxplot(show.legend = FALSE) +
  ylim(min = 0, max = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = .5)) +
  labs(title = paste("Severity Index Rating Comparison for Category: ", categoryname), y = "SIR", x = categoryname )
  })
  }
  })

}


shinyApp(ui = ui, server = server)

```
